global:
  scrape_interval:     15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'kafka'
    static_configs:
      - targets:
        - kafka-1:9876
        - kafka-2:9876
        - kafka-3:9876
        - kafka-m1:9876
        - kafka-m2:9876
        - kafka-m3:9876
