spring:
  output.ansi.enabled: ALWAYS
  application.name: shop

service:
  bootstrap-servers: kafka.local:9093,kafka.local:9094,kafka.local:9095
  schema-registry-url: http://kafka.local:8081
  topic: product
  ssl-truststore-location: C:\module6\docker\kafka-certs\kafka.truststore.jks
  ssl-truststore-password: password3
  sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="shop" password="shop-secret";

logging.level.root: WARN
logging.level.org.example.shop: INFO
logging.charset.console: UTF-8
