apiVersion: 1
groups:
  - orgId: 1
    name: main
    folder: kafka
    interval: 1m
    rules:
      - uid: aekn27dbz47wga
        title: service is down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus_uid
            model:
              disableTextWrap: false
              editorMode: builder
              expr: up{job="kafka"}
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                  - evaluator:
                      params:
                          - 0
                      type: eq
                    operator:
                      type: and
                    query:
                      params:
                          - C
                    reducer:
                      params: []
                      type: last
                    type: query
              datasource:
                  type: __expr__
                  uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: kafka_status_uid
        noDataState: Alerting
        execErrState: Alerting
        for: 1m
        isPaused: false
        notification_settings:
          receiver: grafana-alerting-email
          group_interval: 1m
