{
 "title": "kafka status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "kafka-1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-1:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka-2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-2:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka-3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-3:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka-m1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-m1:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka-m2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-m2:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka-m3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-m3:9876\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}